run:
  build-tags:
    - kurin64
    - kurindebug
linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    # - sql
    - style
    # - test
    - unused
  disable:
    - goimports
    - depguard
    - wsl
    - forcetypeassert
    - nlreturn
linters-settings:
  gofmt:
    simplify: false
  wsl:
    allow-assign-and-anything: true
